name: Github Pages

on:
  pull_request:
    types: [closed]
    branches:
      - master

  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        node:
          - '14'
        platform:
          - ubuntu-18.04

    name: '${{ matrix.platform }} / Node.js v${{ matrix.node }}'
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false
          git config --global user.name "xyz"
          git config --global user.email "x@y.z"

      - name: Checkout Commit
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Pnpm
        run: |
          npm install --g pnpm
          pnpm --version

      - name: Install Dependencies
        run: pnpm install

      - name: Build Website
        run: pnpm run build

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs/.vuepress/dist
